services:
  server:
    build:
      args:
        - VERSION=alt
      dockerfile: Dockerfile
    tty: true
    image: ghcr.io/matatonic/openedai-vision-alt
    env_file: vision-alt.env # your settings go here
    volumes:
      - ./hf_home:/app/hf_home  # for Hugginface model cache
    # be sure to review and run prepare_minigemini.sh before starting a mini-gemini model
      - ./model_zoo:/app/model_zoo # for MiniGemini
      - ./YanweiLi:/app/YanweiLi # for MiniGemini
      - ./model_conf_tests.alt.json:/app/model_conf_tests.json
    ports:
      - 5006:5006
    #runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0', '1'] # Select a gpu, or
              count: all
              capabilities: [gpu]
